name: Push to Qiita
on:
  push:
    branches:
      - main
      - feature/init_ci

permissions:
  contents: read

jobs:
  post:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2

      - name: Get articles_map from atrifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: upload_articles.yml
          name: articles_map

      - run: cat articles_map.txt
      - run: echo testtest.md,idhogehoge > articles_map.txt

      # - run: ID_MAP=`cat readme.md`
      # - run: sh upload_to_qiita.sh `

      - name: Update articles_map
        uses: actions/upload-artifact@v3
        with:
          name: articles_map
          path: articles_map.txt
