name: Push to Qiita
on:
  push:
    branches:
      - main
env:
  ARTICLE_API_URL: https://qiita.com/api/v2/items
  ARTICLE_DIR: articles/
  MAP_FILE_PATH: article_map

jobs:
  post:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Upload to Qiita
        run: bash .github/workflows/upload_to_qiita.sh ${{ env.ARTICLE_DIR }} ${{ secrets.QIITA_ACCESS_TOKEN }} ${{ env.MAP_FILE_PATH }}

      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Update articles_map
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "actions: updated map file"
          git push
        if: steps.diff.outcome == 'failure'
